version: "3.6"

services:
# Start the docker-socket-proxy container for traefik bound to `dockersocketnet`
# Grant read only GET request access to SERVICES/NETWORKS/TASKs apis
# there are no published ports so only other services granted access on the 
# dockersocketnet network can hit this named service @ 2375
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
#   expose:
#     - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICES=1
      - NETWORKS=1
      - TASKS=1
      - CONTAINERS=1
      - IMAGES=1 
    networks:
      - dockersocketnet

# Start Traefik.. note it has access to 2 networks the `dockersocketnet` 
# and the `traefiknet` for containers to proxy to
  traefik:
    image: traefik:maroilles
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      - dockersocketnet
      - traefiknet
    ports:
      - "80:80" 
      - "443:443"
#     - "8080:8080"
    expose:
      - "8080"
    domainname: ${DOMAINNAME}
    dns:
       - 1.1.1.1
    volumes:
      - ${USERDIR}/docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ${USERDIR}/docker/traefik/rules.toml:/etc/traefik/rules.toml:ro
      - ${USERDIR}/docker/traefik/acme:/etc/traefik/acme
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/docker/traefik/log:/var/log
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
#   command:
#     - --web
#     - --accessLog.filePath=/var/log/access.log
#     - --accessLog.filters.statusCodes=400-499
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}" 
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}" 
#      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}" 
      - "traefik.port=8080"
      - "traefik.docker.network=traefiknet"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  plexms:
    container_name: plexms
#   hostname: plex
    restart: always
    image: plexinc/pms-docker
    volumes:
      - ${USERDIR}/docker/plexms:/config
      - ${USERDIR}/Downloads/plex_tmp:/transcode
      - /media/media:/media
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-XXX" #claim redacted
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://192.168.XX.X:32400/"  # IP redacted
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plexms"
      - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefiknet"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"


networks:
  dockersocketnet:
  traefiknet:
