#debug = true

logLevel = "ERROR" 
InsecureSkipVerify = true 
#defaultEntryPoints = ["https", "http"]
defaultEntryPoints = ["https"]

#  entryPoint = "dashboard"
#  dashboard = true
# debug = true
# address = ":8080"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]

#[entryPoints.dashboard]
#address = ":8080"
#[entryPoints.dashboard.auth]
#    [entryPoints.dashboard.auth.basic]
#        users = ["username:encyptedpass"] #redacted
#[retry]

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "admin@mydomain.net" #redacted
storage="/etc/traefik/acme/acme.json"
#caServer = "https://acme-v02.api.letsencrypt.org/directory" #This one is for Production
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" #For staging and testing
entryPoint = "https"
acmeLogging=true 
onDemand = false #create certificate when container is created

[acme.dnsChallenge]
provider = "cloudflare"
delayBeforeCheck = 0
[[acme.domains]]
main = "mydomain.net" #redacted
#   sans = ["name.mydomain.net"]
[[acme.domains]]
main = "*.mydomain.net" #redacted
[traefikLog]
filePath = "/etc/traefik/traefik.log"
   
# Connection to docker host system (docker.sock)
[docker]
endpoint = "tcp://docker-socket-proxy:2375"
domain = "mydomain.net" #redacted
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false
